version: '3'
services:
  web-time-machine-db:
    image: 'postgres:15'
    restart: unless-stopped
    container_name: web-time-machine-db-postgres
    ports:
      - 5432:5432

    environment:
      POSTGRES_DB: web-time-machine-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - web-time-machine-db-data:/var/lib/postgresql/data/

networks:
  default:
    name: web-time-machine-network

volumes:
  web-time-machine-db-data:
    name: web-time-machine-db-data
