on:
  push:
    tags:
      - 'release-chrome'

name: Create Chrome Extension Release

jobs:
  build-chrome:
    name: Create Chrome Extension Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install TurboRepo and dependencies
        run: |
          npm install turbo --global
          npm install

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Run turbo build
        run: turbo run build --filter=@wtm/extension...

      - name: Create ZIP files for Chrome and Firefox
        run: |
          zip -r chrome-extension.zip -j ./build/app_chrome/*

      - name: Upload & release
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: chrome-extension.zip
          extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
